### PR TITLE
Add ability to sort treeview columns by clicking on headers

### PR DESCRIPTION
**Pull request by cofi89**
Hello Gapan,

~~This may be doable via Glade, but since I don't use the thing often and prefer to stay as far from .xml as possible I hope that the "code" way is ok.~~

Tested and verifed on Salix 14.2 & Slackel KDE ( which is a bit behind current "current", but it's the only ISO I had on hdd atm ). :smiley: 

References #1

Signed-off-by: Filip Danilović

<filip@openmailbox.org>

### CODE REVIEW

**Comment by cofi89** [comment]
Update:

I've missed the slight issue brought upfront by this PR.  
Namely the status column is sorted by, well, status ( installed or not ). However the same column also shows the current action, so if you, say, mark a couple of packages for removal, couple for installation and couple for reinstallation, the status column still sorts by status, but now also shows different icons for different actions, which may be confusing/unexpected.  
I'm not sure what would be the best way to deal with it ( besides writing our own sorting function, or moving "actions" into their own column and using treeview filtering ), but the more I look into it the more it seems to be the best to just leave as is? AFAIK, gtk lacks native n-way sorting?? 
  
Btw, the gslapt has the similar issue when viewing marked packages list. Again, due to the lack of n-way sort, one "action" is never sorted by...  

Mandatory screenshot:  

sourcery-sorting

**Comment by cofi89** [comment]
Updated & redone via glade. :smiley:

**Comment by gapan** [comment]
Perfect! Thanks a lot!

**Comment by cofi89** [comment]
You're most welcome! :smiley: 

Btw, gtk3 is about done, I just didn't/don't have enough time to test it properly. Sorry for it taking so long. Hopefully in a week or two I'll be able to get a PR going.

Cheers!

**Comment by gapan** [comment]
Don't worry, there's no rush. We won't need that until the next Salix release anyway.

**Pull request merged**
